language: python

python: 2.7

sudo: false

cache:
    directories:
        - $HOME/.cache/pip
        - _build

addons:
    apt:
        packages: [enchant]

install: pip install sphinx~=1.3 git+https://github.com/fabpot/sphinx-php.git sphinxcontrib-spelling pyenchant

script: 
    - sphinx-build -nW -b html -d _build/doctrees . _build/html
    - make spelling
